categories:
  jobfair2:
    label: 'jobfair2'
  jobfair2.templates:
    label: 'Templates'
    parent: jobfair2
  jobfair2.pages:
    label: 'Pages'
    parent: jobfair2

settings:
  jobfair2.templateRootPath:
    label: 'Templates'
    category: jobfair2.templates
    description: 'Path to template root'
    type: string
    default: 'EXT:jobfair2/Resources/Private/Templates/'
  jobfair2.partialRootPath:
    label: 'Partials'
    category: jobfair2.templates
    description: 'Path to partial root'
    type: string
    default: 'EXT:jobfair2/Resources/Private/Partials/'
  jobfair2.layoutRootPath:
    label: 'Layouts'
    category: jobfair2.templates
    description: 'Path to layout root'
    type: string
    default: 'EXT:jobfair2/Resources/Private/Layouts/'
  jobfair2.storagePid:
    label: 'Default storage PID'
    category: jobfair2.pages
    description: 'Folder that stores all jobs'
    type: page
    default: 0
  jobfair2.pidOfDetailPage:
    label: 'Pid of Detail Page'
    category: jobfair2.pages
    description: 'Page with detail page plugin'
    type: page
    default: 0
  jobfair2.pidOfApplicationForm:
    label: 'Pid of Application Form'
    category: jobfair2.pages
    description: 'Page with online application form for a job'
    type: page
    default: 0
