services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  JWeiland\Jobboard\:
    resource: '../Classes/*'
    exclude: '../Classes/Domain/Model/*'

  JWeiland\Jobboard\ApiModel\ApiMapping:
    shared: false

  JWeiland\Jobboard\ApiModel\JobModel:
    shared: false

  JWeiland\Jobboard\ApiModel\LocationModel:
    shared: false

  JWeiland\Jobboard\Service\ImportService:
    arguments:
      $apiModels: !tagged api.model
